# Conclusions {-}
<!-- If we don't want Conclusion to have a chapter number next to it, we can add the `{-}` attribute. -->

Yield approximation, having significant role in genotype selection, could be much improved by adding leaf health factor in screening and evaluation programs. Likewise, even in classical breeding traits, i.e. crop architecture such as plant height and canopy temperature depression, accuracy of phenotype based selection could be improved through adoption of better designs, which can address multiple sources of spatial heterogeniety in the field. In turn, these extraneous variation could be accounted for through mixed modeling procedures. Therefore, besides improving the precision of estimation with inclusion of leaf health traits, in particular greenness and relative chlorophyll content measures at early post-anthesis period, certain traits such as thousand kernel weight, plant height, flag leaf area, canopy temperature depression, days to heading and days to anthesis benefitted the most by modeling of spatial covariates.
